[package]
name = "snake_game_client"
version.workspace = true
edition.workspace = true

[[bin]]
name = "snake_game_client"
path = "src/main.rs"

[dependencies]
common = { path = "../common" }
tonic = "0.12"
tokio = { version = "1.0", features = ["full"] }
names = { version = "0.14", default-features = false }
