[package]
name = "mini_games_server"
version.workspace = true
edition.workspace = true

[lib]
name = "mini_games_server"
path = "src/lib.rs"

[[bin]]
name = "mini_games_server"
path = "src/main.rs"

[[bench]]
name = "minimax_bench"
harness = false

[dependencies]
common = { path = "../common" }
tonic = "0.14.2"
tokio = { version = "1.0", features = ["full"] }
tokio-stream = "0.1"
clap = { version = "4.5", features = ["derive"] }
rand = "0.9.2"

[dev-dependencies]
criterion = "0.5"
