[package]
name = "snake_game_server"
version.workspace = true
edition.workspace = true

[[bin]]
name = "snake_game_server"
path = "src/main.rs"

[dependencies]
common = { path = "../common" }
tonic = "0.14.2"
tokio = { version = "1.0", features = ["full"] }
tokio-stream = "0.1"
clap = { version = "4.5", features = ["derive"] }
