[package]
name = "common"
version.workspace = true
edition.workspace = true

[dependencies]
tonic = "0.12"
prost = "0.13"
tokio = { version = "1.0", features = ["full"] }
rand = "0.8"
chrono = "0.4"

[build-dependencies]
tonic-build = "0.12"
protoc-bin-vendored = "3.2.0"
